 language: node_js
 node_js:
   - "0.10"
   - "0.8"
   - "0.7"
 before_install:
 - sudo npm cache clear; sudo apt-get update && sudo apt-get install -y redis-server libasound2-dev
 after_success: grunt publish --verbose
